app = 'velocity-preview-containers'
primary_region = 'ord'

[build]
  image = 'ghcr.io/tythanhdoan/velocity/velocity-preview-container:latest'

[env]
  NODE_ENV = 'production'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[http_service.checks]]
  method = 'get'
  path = '/health'
  grace_period = '5s'
  interval = '10s'
  timeout = '2s'

[[services]]
  http_checks = []
  internal_port = 8080
  protocol = "tcp"
  script_checks = []

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

# Enable wildcard routing and experimental features
[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1