app = 'velocity-preview-containers'
primary_region = 'ord'

[build]
  image = 'ghcr.io/tdoan35/velocity/velocity-preview-container:latest'

[env]
  NODE_ENV = 'production'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[http_service.checks]]
  method = 'get'
  path = '/health'
  grace_period = '5s'
  interval = '10s'
  timeout = '2s'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1